version: '3'
services:
  sentry:
    image: getsentry/sentry:latest
    ports:
      - "9000:9000"
    environment:
      - SENTRY_SECRET_KEY=akjsdhfljkahlskjdsfhkahkj
      - SENTRY_POSTGRES_HOST=sentry-postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentrypassword
      - SENTRY_REDIS_HOST=sentry-redis

  sentry-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=sentrypassword
      - POSTGRES_USER=sentry
      - POSTGRES_DB=sentry

  sentry-redis:
    image: redis:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"


  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    volumes:
      - ./elk/logstash/:/usr/share/logstash/config/
    command: logstash -f /usr/share/logstash/config/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200